---
-
  hosts: all
  tasks:
    -
      name: "uninstall Java JRE rpm from a local file"
      yum:
        name: "*java*"
        state: absent
    -
      name: "install Java JRE rpm from a local file"
      yum:
        name: "*java*1.8*"
        state: present
    -
      copy:
        dest: /tmp/.
        src: target/oms-product-service-0.0.1-SNAPSHOT.jar
      name: "Copy Artifact"
    -
      name: "Run Artifact"
      shell: nohup java -jar /tmp/oms-product-service-0.0.1-SNAPSHOT.jar &
